import { StyleSheet } from 'react-native'
import { COLORS, FONTS, rgba } from './apkTheme'

export const happyApkStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.canvas },
  fill: { flex: 1 },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14, paddingHorizontal: 28 },
  loadingTitle: { color: COLORS.textPrimary, fontSize: 23, fontFamily: FONTS.displayBold },
  loadingBody: { color: COLORS.textMuted, fontSize: 14, fontFamily: FONTS.body, textAlign: 'center' },

  backgroundOrb: { position: 'absolute', borderRadius: 999, opacity: 0.22 },
  backgroundOrbTop: { width: 220, height: 220, top: -84, right: -16, backgroundColor: rgba(COLORS.blue, 0.42) },
  backgroundOrbBottom: { width: 210, height: 210, bottom: 88, left: -68, backgroundColor: rgba(COLORS.cyan, 0.24) },

  scrollContent: { paddingHorizontal: 12, paddingTop: 12, paddingBottom: 128, gap: 12 },

  windowShell: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(13, 18, 28, 0.86)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 8,
  },
  windowTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  titleGroup: { flex: 1, gap: 2 },
  windowTitle: { color: COLORS.textPrimary, fontSize: 24, fontFamily: FONTS.displayBold },
  windowTime: { color: '#d9e4f4', fontSize: 13, fontFamily: FONTS.monoSemibold },
  chromeGroup: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  chromePill: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(72, 78, 96, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chromePillWide: { minWidth: 88 },
  chromePillText: { color: COLORS.textPrimary, fontSize: 12, fontFamily: FONTS.bodySemibold },
  headerMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  syncSummaryText: { flex: 1, color: COLORS.textSecondary, fontSize: 12, lineHeight: 17, fontFamily: FONTS.body },
  quickStatsRow: { flexDirection: 'row', gap: 8 },
  quickStat: {
    minWidth: 54,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(20, 27, 39, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    gap: 2,
  },
  quickStatLabel: { color: COLORS.textMuted, fontSize: 10, fontFamily: FONTS.bodyMedium },
  quickStatValue: { color: COLORS.textPrimary, fontSize: 15, fontFamily: FONTS.monoSemibold },

  filterPanel: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: COLORS.panelSoft,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  panelHeader: { gap: 2 },
  panelTitle: { color: COLORS.textPrimary, fontSize: 15, fontFamily: FONTS.displayMedium },
  panelCaption: { color: COLORS.textMuted, fontSize: 11, fontFamily: FONTS.body },
  filterRail: { gap: 8 },

  sectionHeadingRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 14, marginTop: 2 },
  sectionHeading: { color: COLORS.textPrimary, fontSize: 19, fontFamily: FONTS.displayBold },
  sectionCaption: { color: COLORS.textMuted, fontSize: 11, lineHeight: 16, fontFamily: FONTS.body, marginTop: 2 },
  sectionCount: { color: COLORS.textPrimary, fontSize: 20, fontFamily: FONTS.monoSemibold },

  emptyCard: { borderRadius: 22, borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.panel, padding: 18, gap: 8 },
  emptyTitle: { color: COLORS.textPrimary, fontSize: 18, fontFamily: FONTS.displayMedium },
  emptyBody: { color: COLORS.textMuted, fontSize: 14, lineHeight: 20, fontFamily: FONTS.body },

  floatingComposer: {
    position: 'absolute',
    right: 16,
    bottom: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 54,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: COLORS.textPrimary,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
  },
  floatingComposerPlus: { color: '#08101a', fontSize: 25, lineHeight: 26, fontFamily: FONTS.displayBold },
  floatingComposerText: { color: '#08101a', fontSize: 15, fontFamily: FONTS.bodySemibold },

  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: COLORS.overlay },
  sheet: {
    maxHeight: '88%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#0a111d',
    borderTopWidth: 1,
    borderColor: COLORS.lineStrong,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
  },
  editorSheet: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#0a111d',
    borderTopWidth: 1,
    borderColor: COLORS.lineStrong,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
  },
  sheetHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 14 },
  sheetKicker: { color: COLORS.cyan, fontSize: 12, fontFamily: FONTS.monoSemibold, textTransform: 'uppercase' },
  sheetTitle: { color: COLORS.textPrimary, fontSize: 24, lineHeight: 28, fontFamily: FONTS.displayBold, marginTop: 4 },
  sheetCloseButton: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
  },
  sheetCloseText: { color: COLORS.textSecondary, fontSize: 12, fontFamily: FONTS.bodySemibold },
  sheetScrollContent: { gap: 14 },
  sheetCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: COLORS.panel,
    padding: 16,
    gap: 12,
  },
  sheetCardTitle: { color: COLORS.textPrimary, fontSize: 18, lineHeight: 22, fontFamily: FONTS.displayMedium },
  sheetCardBody: { color: COLORS.textMuted, fontSize: 13, lineHeight: 19, fontFamily: FONTS.body },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  switchCopy: { flex: 1, gap: 3 },
  switchLabel: { color: COLORS.textPrimary, fontSize: 15, fontFamily: FONTS.bodySemibold },
  switchHint: { color: COLORS.textMuted, fontSize: 12, lineHeight: 18, fontFamily: FONTS.body },
  textField: {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.lineStrong,
    backgroundColor: 'rgba(255,255,255,0.04)',
    paddingHorizontal: 14,
    color: COLORS.textPrimary,
    fontSize: 14,
    fontFamily: FONTS.body,
  },
  sheetButtonRow: { flexDirection: 'row', gap: 10 },
  primarySheetButton: { flex: 1, minHeight: 46, borderRadius: 16, backgroundColor: COLORS.textPrimary, alignItems: 'center', justifyContent: 'center' },
  primarySheetButtonText: { color: '#07111d', fontSize: 14, fontFamily: FONTS.bodySemibold },
  secondarySheetButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondarySheetButtonText: { color: COLORS.textPrimary, fontSize: 14, fontFamily: FONTS.bodySemibold },
  segmentRow: { flexDirection: 'row', gap: 10 },
  segmentButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  segmentButtonActive: { backgroundColor: rgba(COLORS.cyan, 0.16), borderColor: rgba(COLORS.cyan, 0.28) },
  segmentButtonText: { color: COLORS.textPrimary, fontSize: 13, fontFamily: FONTS.bodySemibold },
  rangeRow: { flexDirection: 'row', gap: 10 },
  rangeField: { flex: 1 },
  rangeSummary: { color: COLORS.textSecondary, fontSize: 12, fontFamily: FONTS.body },

  editorMeta: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12, flexWrap: 'wrap' },
  statusBadge: { minHeight: 28, paddingHorizontal: 10, borderRadius: 999, borderWidth: 1, justifyContent: 'center' },
  statusBadgeText: { fontSize: 11, fontFamily: FONTS.bodySemibold },
  editorMetaText: { color: COLORS.textMuted, fontSize: 12, fontFamily: FONTS.body },
  editorInput: {
    minHeight: 220,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.lineStrong,
    backgroundColor: 'rgba(255,255,255,0.04)',
    paddingHorizontal: 16,
    paddingVertical: 16,
    color: COLORS.textPrimary,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: FONTS.body,
    marginBottom: 16,
  },

  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  actionGridButton: {
    width: '48%',
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  actionGridButtonText: { color: COLORS.textPrimary, fontSize: 13, lineHeight: 18, textAlign: 'center', fontFamily: FONTS.bodySemibold },
  swatchRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  swatch: { width: 38, height: 38, borderRadius: 999, borderWidth: 2, borderColor: 'rgba(255,255,255,0.22)' },
  dangerButton: {
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: rgba(COLORS.red, 0.16),
    borderWidth: 1,
    borderColor: rgba(COLORS.red, 0.28),
    justifyContent: 'center',
    alignItems: 'center',
  },
  dangerButtonText: { color: '#ffd7ce', fontSize: 14, fontFamily: FONTS.bodySemibold },
})
